package com.droidrun.portal.events.model

enum class EventType {
    NOTIFICATION,
    NOTIFICATION_POSTED,
    NOTIFICATION_REMOVED,
    APP_ENTERED,
    APP_EXITED,
    BATTERY_LOW,
    BATTERY_OKAY,
    BATTERY_LEVEL_CHANGED,
    POWER_CONNECTED,
    POWER_DISCONNECTED,
    USER_PRESENT,
    NETWORK_CONNECTED,
    NETWORK_TYPE_CHANGED,
    SMS_RECEIVED,
    PING,
    PONG,
    UNKNOWN
}
